export const CHANGE_SEARCH_FILED = 'CHANGE_SEARCH_FILED';
export const FECTH_ROBOTS_PENDING = 'FECTH_ROBOTS_PENDING';
export const FECTH_ROBOTS_SUCCESS = 'FECTH_ROBOTS_SUCCESS';
export const FECTH_ROBOTS_FAIL = 'FECTH_ROBOTS_FAIL';

